### ISSUE TITLE
update with flutter 3.0

### ISSUE THREAD

**Issue by srcho** [mpcreza/mini_music_visualizer#1]
Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/lib/mini_music_visualizer.dart:93
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.**instance!**.addPostFrameCallback((timeStamp) {

when app build, i can see this warning log with flutter 3.0

**Comment by mpcreza** [comment]
Please upgrade package to 1.0.2
