### ISSUE TITLE
Controll the play and pause of  the animation from my code.

### ISSUE THREAD

**Issue by ChristineWasike** [mpcreza/mini_music_visualizer#2]
Great package. How can I control the animation (when it starts and stops) based on the audio player button I have? At the moment, the animation is playing throughout.
Thanks.
<img width="129" alt="Screenshot 2022-12-05 at 12 54 08" src="https://user-images.githubusercontent.com/28866174/205607520-c3f38648-f580-47a9-b95c-8d4f77b244a1.png">

**Comment by mpcreza** [comment]
Hi
Unfortunately, it is not possible to control the animation at the moment, but I will add this soon.
I suggest you use Visibility based on playing or stopping the player for now.

**Comment by mpcreza** [comment]
Play and pause support was added in the latest version(Thanks to [MrLittleWhite](https://github.com/MrLittleWhite)).
